### ISSUE TITLE
Does toc-me work on private repositories?

### ISSUE THREAD

**Issue by gr2m** [pholleran/toc-me#15]
I just created a pull request on a private repository. There are two changed *.md files with the `<!-- toc -->` placeholder, but I didn’t get an update from toc-me with the table of contents.

**Comment by pholleran** [comment]
Odd. I am running it on a number of private repos without issue. If you don't mind sharing the org name I can check the webhook payloads and see if anything was sent.

**Comment by gr2m** [comment]
I made the repository public now, it was private when I installed the app: https://github.com/gr2m/twitter-together

I ended up adding the TOCs using the CLI tool
